name: A job to run the dockerfile
on: [push]

jobs:
  docker_runner_job:
    runs-on: ubuntu-20.04
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: run the docker step
        uses: ./.github/actions/
